import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const CATEGORIES = ['Actors', 'Models', 'Presenters', 'Musicians', 'Filmmakers', 'Voice Artists', 'Dancers', 'Photographers', 'Editors', 'Writers'];
const PUBLIC_FILTERS = ['All categories', ...CATEGORIES];

async function api(path, opt = {}) { const token = localStorage.getItem('rot_access'); const headers = { 'Content-Type': 'application/json', ...(opt.headers || {}) }; if (token) headers.Authorization = `Bearer ${token}`; const r = await fetch(API + path, { ...opt, headers }); const d = await r.json().catch(() => ({})); if (!r.ok) throw Error(d.error || 'Request failed'); return d; }
function saveAuth(d) { localStorage.setItem('rot_access', d.accessToken); localStorage.setItem('rot_refresh', d.refreshToken); localStorage.setItem('rot_user', JSON.stringify(d.user)); return d.user; }
function loadRazorpay() { return new Promise((resolve, reject) => { if (window.Razorpay) return resolve(); const s = document.createElement('script'); s.src = 'https://checkout.razorpay.com/v1/checkout.js'; s.onload = resolve; s.onerror = () => reject(Error('Unable to load payment checkout')); document.body.appendChild(s); }); }
function initials(name = '') { return name.split(' ').filter(Boolean).slice(0, 2).map(x => x[0]).join('').toUpperCase() || 'RT'; }

function App() {
    const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('rot_user') || 'null'));
    const [profiles, setProfiles] = useState([]); const [category, setCategory] = useState(''); const [location, setLocation] = useState('');
    const [search, setSearch] = useState(''); const [sex, setSex] = useState(''); const [minAge, setMinAge] = useState(''); const [maxAge, setMaxAge] = useState(''); const [minHeight, setMinHeight] = useState(''); const [maxHeight, setMaxHeight] = useState('');
    const [modal, setModal] = useState(null); const [selected, setSelected] = useState(null); const [toast, setToast] = useState(''); const [loading, setLoading] = useState(false);
    const recruiter = Boolean(user && (user.role === 'RECRUITER' || user.role === 'SUPER_ADMIN'));
    const load = async () => { setLoading(true); try { const q = new URLSearchParams(); if (category) q.set('category', category); if (location) q.set('location', location); if (recruiter) { [['search', search], ['sex', sex], ['minAge', minAge], ['maxAge', maxAge], ['minHeight', minHeight], ['maxHeight', maxHeight]].forEach(([k, v]) => v && q.set(k, v)); } const d = await api('/talents?' + q); setProfiles(d.items || []); } catch (e) { setProfiles([]); setToast(e.message) } finally { setLoading(false) } };
    useEffect(() => { load() }, [category, location, search, sex, minAge, maxAge, minHeight, maxHeight, user?.role]);
    function auth(d) { const u = saveAuth(d); setUser(u); setModal(u.role === 'TALENT' ? 'profile' : 'dashboard'); setToast(u.role === 'TALENT' ? 'Build your profile to enter the room.' : 'Welcome back.'); }
    async function logout() { try { await api('/auth/logout', { method: 'POST', body: JSON.stringify({ refreshToken: localStorage.getItem('rot_refresh') }) }) } catch { } localStorage.clear(); setUser(null); setModal(null); load(); }
    return <div className="app"><header className="nav"><a className="logo" href="#top">room<span>of</span>talents<span className="dot">.</span>in</a><nav><a href="#discover">Discover</a><a href="#plans">Membership</a><a href="#how">How it works</a></nav><div className="nav-actions">{user ? <button className="glass" onClick={() => setModal('dashboard')}>{user.name.split(' ')[0]} ↗</button> : <><button className="text-btn" onClick={() => setModal('login')}>Log in</button><button className="solid" onClick={() => setModal('register')}>Join the room ↗</button></>}</div></header>
        <main id="top"><section id="discover" className="directory"><div className="directory-top"><div><div className="eyebrow">ROOM OF TALENTS / LIVE CASTING DIRECTORY</div><div className="directory-title"><h1>Find the <i>face.</i></h1><p>Real people. Real profiles. Ready for the next production.</p></div></div><div className="live-count"><strong>{String(profiles.length).padStart(2, '0')}</strong><span>visible talents</span></div></div>
            <div className="public-search"><div className="search-main"><span>⌕</span><input value={location} onChange={e => setLocation(e.target.value)} placeholder="Search by place — Kochi, Mumbai, Bengaluru..." /><button className="solid" onClick={load}>Find talent ↗</button></div><div className="category-strip"><button className={!category ? 'active' : ''} onClick={() => setCategory('')}>All</button>{CATEGORIES.map(c => <button key={c} className={category === c ? 'active' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div></div>
            {recruiter && (
                <RecruiterFilters
                    {...{
                        search,
                        setSearch,
                        sex,
                        setSex,
                        minAge,
                        setMinAge,
                        maxAge,
                        setMaxAge,
                        minHeight,
                        setMinHeight,
                        maxHeight,
                        setMaxHeight,
                        clear: () => {
                            setSearch('');
                            setSex('');
                            setMinAge('');
                            setMaxAge('');
                            setMinHeight('');
                            setMaxHeight('');
                        },
                    }}
                />
            )}

            <div className="directory-bar">
                <span>
                    {recruiter
                        ? 'RECRUITER SEARCH / ADVANCED FILTERS'
                        : 'PUBLIC DIRECTORY / PLACE + CATEGORY'}
                </span>
                <span>{loading ? 'UPDATING…' : 'DRAG TO EXPLORE \u2192'}</span>
            </div>

            {profiles.length ? (
                <div className="cards">
                    {profiles.map((p, i) => (
                        <TalentCard key={p.id} p={p} index={i} onClick={() => setSelected(p)} />
                    ))}
                </div>
            ) : (
                <div className="empty">
                    <span>NO TALENTS YET</span>
                    <h2>{loading ? 'Finding people…' : 'The room is waiting.'}</h2>
                    <p>Once subscribed talent profiles are live, they will appear here.</p>
                    <button className="solid" onClick={() => setModal('register')}>
                        Create a profile &#8599;
                    </button>
                </div>
            )}
        </section>
            <section id="plans" className="plans"><div className="eyebrow">MEMBERSHIP / ACCESS</div><h2>Choose how you<br /><i>enter the room.</i></h2><div className="plan-grid"><Plan name="Talent PRO" price="499" note="For talents" features={['Public profile discovery', 'PRO contact network', 'Build a searchable casting profile']} onClick={() => setModal('register')} /><Plan name="Talent Exclusive" price="1,499" note="For talents who want a private network" features={['Everything in PRO', 'Exclusive profile visibility controls', 'Exclusive members can exchange contacts']} onClick={() => setModal('register')} /><Plan name="Elite Recruiter" price="4,999" note="For hiring teams" features={['Advanced talent search', 'Age, sex and height filters', 'Access eligible talent contacts']} onClick={() => setModal('register')} /></div></section>
            <section id="how" className="how"><div className="eyebrow">THE LOOP</div><h2>Show up.<br />Get <i>seen.</i><br />Get cast.</h2><div className="steps"><div><b>01</b><h3>Build</h3><p>Create a visual profile with your craft, location, details and portfolio.</p></div><div><b>02</b><h3>Discover</h3><p>Recruiters search the directory and narrow the room to the right people.</p></div><div><b>03</b><h3>Connect</h3><p>Membership controls who can access direct contact information.</p></div></div></section></main><footer>roomoftalents.in <span>The room for people who make things happen.</span></footer>
        {selected && <Modal title={selected.displayName} close={() => setSelected(null)} wide><ProfileView talent={selected} user={user} onLogin={() => { setSelected(null); setModal('login') }} setToast={setToast} /></Modal>}
        {modal && <Modal title={modal === 'login' ? 'Welcome back' : modal === 'register' ? 'Join the room' : modal === 'profile' ? 'Your talent profile' : modal === 'subscribe' ? 'Choose your membership' : 'Command centre'} close={() => setModal(null)} wide={modal === 'dashboard'}><Form mode={modal} user={user} onAuth={auth} onLogout={logout} setToast={setToast} setModal={setModal} /></Modal>}{toast && <button className="toast" onClick={() => setToast('')}>{toast} ×</button>}</div>
}
function RecruiterFilters(p) { return <div className="advanced"><div className="advanced-head"><div><span className="eyebrow">ELITE SEARCH</span><strong>Refine the room</strong></div><button className="text-btn" onClick={p.clear}>Clear filters</button></div><div className="advanced-grid"><input value={p.search} onChange={e => p.setSearch(e.target.value)} placeholder="Name, role, skill..." /><select value={p.sex} onChange={e => p.setSex(e.target.value)}><option value="">Any sex</option><option>Female</option><option>Male</option><option>Other</option></select><input type="number" value={p.minAge} onChange={e => p.setMinAge(e.target.value)} placeholder="Age from" /><input type="number" value={p.maxAge} onChange={e => p.setMaxAge(e.target.value)} placeholder="Age to" /><input type="number" value={p.minHeight} onChange={e => p.setMinHeight(e.target.value)} placeholder="Height from cm" /><input type="number" value={p.maxHeight} onChange={e => p.setMaxHeight(e.target.value)} placeholder="Height to cm" /></div></div> }
function TalentCard({ p, index, onClick }) { return <article className="talent-card" onClick={onClick}><div className="photo"><div className="photo-fallback"><span>{initials(p.displayName)}</span></div>{p.imageUrl && <img src={p.imageUrl} alt={p.displayName} onError={e => e.currentTarget.style.display = 'none'} />}<span className="availability"><em /> Available</span><b className="card-arrow">↗</b><div className="card-index">{String(index + 1).padStart(2, '0')}</div></div><div className="talent-copy"><div><h3>{p.displayName}</h3><p>{p.professionalRole}</p></div><small>{p.location}</small></div><div className="tags">{(p.categories || []).slice(0, 3).map(c => <span key={c}>{c}</span>)}</div></article> }
function ProfileView({ talent, user, onLogin, setToast }) { const [contact, setContact] = useState(null); const [busy, setBusy] = useState(false); async function reveal() { if (!user) { onLogin(); return } setBusy(true); try { const d = await api(`/talents/${talent.id}/contact`); setContact(d) } catch (e) { setToast(e.message) } finally { setBusy(false) } } return <div className="profile-view"><div className="profile-hero"><div className="profile-photo"><div className="photo-fallback"><span>{initials(talent.displayName)}</span></div>{talent.imageUrl && <img src={talent.imageUrl} alt={talent.displayName} onError={e => e.currentTarget.style.display = 'none'} />}</div><div><div className="eyebrow">PROFILE / {talent.location}</div><h3>{talent.displayName}</h3><p className="role-line">{talent.professionalRole}</p><div className="tags">{(talent.categories || []).map(c => <span key={c}>{c}</span>)}</div></div></div><div className="profile-body"><p>{talent.bio || 'This talent has not added a biography yet.'}</p>{(talent.age || talent.sex || talent.heightCm) && <div className="facts">{talent.age && <span><b>{talent.age}</b> age</span>}{talent.sex && <span><b>{talent.sex}</b> sex</span>}{talent.heightCm && <span><b>{talent.heightCm} cm</b> height</span>}</div>}{(talent.skills || []).length > 0 && <div className="skill-row">{talent.skills.map(s => <span key={s}>{s}</span>)}</div>}<div className="contact-box"><div><span className="eyebrow">DIRECT CONTACT</span><strong>{contact ? `${contact.phone || 'No phone'} · ${contact.email}` : 'Available according to membership'}</strong></div><button className="solid" disabled={busy} onClick={reveal}>{contact ? 'Contact unlocked' : busy ? 'Checking…' : 'Reveal contact ↗'}</button></div></div></div> }
function Plan({ name, price, note, features, onClick }) { return <div className="plan"><div className="eyebrow">{name}</div><div className="price">₹{price}<small>/year</small></div><p>{note}</p><ul>{features.map(f => <li key={f}>✓ {f}</li>)}</ul><button className="solid" onClick={onClick}>Get started ↗</button></div> }
function Modal({ title, close, children, wide }) { return <div className="backdrop" onClick={close}><div className={`modal ${wide ? 'modal-wide' : ''}`} onClick={e => e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">ROOMOFTALENTS.IN</div><h2>{title}</h2>{children}</div></div> }
function Form({ mode, user, onAuth, onLogout, setToast, setModal }) {
    const [kind, setKind] = useState('TALENT'); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [status, setStatus] = useState(null);
    const [f, setF] = useState({ name: '', email: '', password: '', displayName: '', professionalRole: '', categories: [], location: '', age: '', sex: '', heightCm: '', bio: '', phone: '', portfolioUrl: '', imageUrl: '', skills: '' }); const set = (k, v) => setF(x => ({ ...x, [k]: v }));
    useEffect(() => { if (mode === 'profile' && user) api('/talents/me').then(d => { if (d.talent) setF(x => ({ ...x, ...d.talent, skills: (d.talent.skills || []).join(',') })); setStatus(d) }).catch(e => setError(e.message)); }, [mode, user]);
    async function submit(e) { e.preventDefault(); setError(''); setLoading(true); try { let d; if (mode === 'login') d = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email: f.email, password: f.password }) }); else if (mode === 'register') d = await api('/auth/register', { method: 'POST', body: JSON.stringify({ name: f.name, email: f.email, password: f.password, role: kind }) }); else if (mode === 'profile') d = await api('/talents', { method: 'POST', body: JSON.stringify({ ...f, age: f.age || null, heightCm: f.heightCm || null, skills: f.skills.split(',').map(x => x.trim()).filter(Boolean), categories: f.categories }) }); if (d?.user) onAuth(d); else { setStatus(d); setToast(d.message || 'Saved successfully.'); if (mode === 'profile' && !d.hasActivePro) setModal('subscribe'); } } catch (e) { setError(e.message) } finally { setLoading(false) } }
    async function subscribe(plan) { setLoading(true); setError(''); try { await loadRazorpay(); const order = await api('/subscriptions/order', { method: 'POST', body: JSON.stringify({ plan }) }); const payment = new window.Razorpay({ key: order.keyId, amount: order.amount, currency: order.currency, name: 'RoomOfTalents.in', description: plan === 'EXCLUSIVE' ? 'Talent Exclusive' : 'Talent PRO', order_id: order.orderId, prefill: { name: user?.name, email: user?.email }, handler: async response => { try { const d = await api('/subscriptions/verify', { method: 'POST', body: JSON.stringify(response) }); setToast(d.message); setModal('dashboard'); } catch (e) { setError(e.message) } }, modal: { ondismiss: () => setLoading(false) } }); payment.open(); } catch (e) { setError(e.message); setLoading(false) } }
    if (mode === 'subscribe') return <div className="membership-choice"><p>Choose the access level for your talent profile.</p><div className="mini-plans"><button onClick={() => subscribe('PRO')} disabled={loading}><b>PRO</b><span>₹499 / year</span><small>Public discovery + PRO contact network</small></button><button onClick={() => subscribe('EXCLUSIVE')} disabled={loading}><b>EXCLUSIVE</b><span>₹1,499 / year</span><small>Private exclusive network + PRO benefits</small></button></div><button className="glass full" onClick={() => setModal('profile')}>Back to profile</button></div>;
    if (mode === 'dashboard') return user?.role === 'SUPER_ADMIN' ? <AdminPanel setToast={setToast} onLogout={onLogout} /> : <div className="account"><div className="account-head"><div className="avatar">{initials(user?.name)}</div><div><span className="eyebrow">ACCOUNT</span><h3>{user?.name}</h3><p>{user?.email}</p></div><span className="pill">{user?.role}</span></div>{user?.role === 'TALENT' && <><button className="solid full" onClick={() => setModal('profile')}>Manage profile ↗</button><button className="glass full" onClick={() => setModal('subscribe')}>Manage membership ↗</button></>}{user?.role === 'RECRUITER' && <p className="account-note">Your recruiter account can use advanced filters directly on the talent directory. Upgrade to Elite to unlock eligible contact details.</p>}<button className="glass full" onClick={onLogout}>Log out</button></div>;
    if (mode === 'login') return <form onSubmit={submit}><Field label="Email"><input required type="email" value={f.email} onChange={e => set('email', e.target.value)} /></Field><Field label="Password"><input required type="password" value={f.password} onChange={e => set('password', e.target.value)} /></Field><Error text={error} /><button className="solid full" disabled={loading}>{loading ? 'Signing in…' : 'Log in ↗'}</button></form>;
    if (mode === 'register') return <form onSubmit={submit}><Field label="Account type"><select value={kind} onChange={e => setKind(e.target.value)}><option value="TALENT">Talent</option><option value="RECRUITER">Recruiter / Production</option></select></Field><Field label="Full name"><input required value={f.name} onChange={e => set('name', e.target.value)} /></Field><Field label="Email"><input required type="email" value={f.email} onChange={e => set('email', e.target.value)} /></Field><Field label="Password"><input required minLength="8" type="password" value={f.password} onChange={e => set('password', e.target.value)} /></Field><Error text={error} /><button className="solid full" disabled={loading}>{loading ? 'Creating…' : 'Create account ↗'}</button></form>;
    return <form className="profile-form" onSubmit={submit}><div className="form-intro"><span className="eyebrow">YOUR CASTING PROFILE</span><p>{status?.hasActivePro ? 'Your profile is live.' : 'Fill this once and your profile can become discoverable after you activate PRO.'}</p></div><div className="two-col"><Field label="Display name"><input required value={f.displayName} onChange={e => set('displayName', e.target.value)} /></Field><Field label="Professional role"><input required value={f.professionalRole} onChange={e => set('professionalRole', e.target.value)} /></Field></div><Field label={`Categories (${f.categories.length}/3)`}><div className="category-picker">{CATEGORIES.map(c => <button type="button" key={c} className={f.categories.includes(c) ? 'selected' : ''} disabled={!f.categories.includes(c) && f.categories.length >= 3} onClick={() => set('categories', f.categories.includes(c) ? f.categories.filter(x => x !== c) : [...f.categories, c])}>{c}</button>)}</div></Field><div className="two-col"><Field label="Location"><input required value={f.location} onChange={e => set('location', e.target.value)} /></Field><Field label="Sex"><select value={f.sex || ''} onChange={e => set('sex', e.target.value)}><option value="">Prefer not to say</option><option>Female</option><option>Male</option><option>Other</option></select></Field><Field label="Age"><input type="number" min="1" max="120" value={f.age || ''} onChange={e => set('age', e.target.value)} /></Field><Field label="Height (cm, optional)"><input type="number" min="50" max="250" value={f.heightCm || ''} onChange={e => set('heightCm', e.target.value)} /></Field></div><Field label="Bio"><textarea value={f.bio || ''} onChange={e => set('bio', e.target.value)} /></Field><div className="two-col"><Field label="Phone"><input value={f.phone || ''} onChange={e => set('phone', e.target.value)} /></Field><Field label="Portfolio URL"><input type="url" value={f.portfolioUrl || ''} onChange={e => set('portfolioUrl', e.target.value)} /></Field></div><div className="two-col"><Field label="Profile image URL"><input type="url" value={f.imageUrl || ''} onChange={e => set('imageUrl', e.target.value)} /></Field><Field label="Skills (comma separated)"><input value={f.skills || ''} onChange={e => set('skills', e.target.value)} /></Field></div><Error text={error} /><button className="solid full" disabled={loading || f.categories.length < 1}>{loading ? 'Saving…' : 'Save profile ↗'}</button>{status?.hasActivePro === false && <button type="button" className="glass full" onClick={() => setModal('subscribe')}>Activate PRO ↗</button>}</form>;
}
function AdminPanel({ setToast, onLogout }) {
    const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(''); const [query, setQuery] = useState(''); const [role, setRole] = useState('ALL'); const [status, setStatus] = useState('ALL'); const [newUser, setNewUser] = useState({ name: '', email: '', password: '', role: 'TALENT' });
    const load = () => api('/admin/subscriptions/users').then(d => setUsers(d.users || [])).catch(e => setToast(e.message)).finally(() => setLoading(false)); useEffect(() => { load() }, []);
    const filtered = useMemo(() => users.filter(u => { const q = query.toLowerCase(); return (!q || [u.name, u.email, u.talent?.professionalRole, u.talent?.location].join(' ').toLowerCase().includes(q)) && (role === 'ALL' || u.role === role) && (status === 'ALL' || (status === 'ACTIVE' ? u.isActive : !u.isActive)); }), [users, query, role, status]);
    const stats = { total: users.length, talents: users.filter(u => u.role === 'TALENT').length, recruiters: users.filter(u => u.role === 'RECRUITER').length, active: users.filter(u => u.isActive).length };
    async function grant(userId, plan) { setWorking(`${userId}-${plan}`); try { const d = await api('/admin/subscriptions/grant', { method: 'POST', body: JSON.stringify({ userId, plan, durationDays: 365 }) }); setToast(d.message); await load() } catch (e) { setToast(e.message) } finally { setWorking('') } }
    async function toggle(u) { try { await api(`/admin/users/${u.id}/active`, { method: 'PATCH', body: JSON.stringify({ isActive: !u.isActive }) }); setToast(`${u.name} ${u.isActive ? 'disabled' : 'enabled'}`); await load() } catch (e) { setToast(e.message) } }
    async function create(e) { e.preventDefault(); try { await api('/admin/users', { method: 'POST', body: JSON.stringify(newUser) }); setNewUser({ name: '', email: '', password: '', role: 'TALENT' }); setToast('Account created'); await load() } catch (e) { setToast(e.message) } }
    async function remove(u) { if (!confirm(`Delete ${u.name} permanently?`)) return; try { await api(`/admin/users/${u.id}`, { method: 'DELETE' }); setToast('User deleted'); await load() } catch (e) { setToast(e.message) } }
    return <section className="admin"><div className="admin-hero"><div><span className="eyebrow">SUPER ADMIN / COMMAND CENTRE</span><h3>Run the room.</h3><p>Create people, control access and manage complimentary memberships.</p></div><div className="admin-hero-actions"><button className="glass" onClick={onLogout}>Log out ↗</button><button className="solid" onClick={() => document.getElementById('create-account')?.scrollIntoView({ behavior: 'smooth' })}>+ Create account</button></div></div><div className="stat-grid"><Stat n={stats.total} label="Accounts" /><Stat n={stats.talents} label="Talents" /><Stat n={stats.recruiters} label="Recruiters" /><Stat n={stats.active} label="Active" /></div><div id="create-account" className="create-card"><div><span className="eyebrow">CREATE ACCOUNT</span><strong>Put someone in the room</strong></div><form onSubmit={create}><input placeholder="Full name" required value={newUser.name} onChange={e => setNewUser({ ...newUser, name: e.target.value })} /><input type="email" placeholder="Email" required value={newUser.email} onChange={e => setNewUser({ ...newUser, email: e.target.value })} /><input type="password" placeholder="Temporary password" minLength="8" required value={newUser.password} onChange={e => setNewUser({ ...newUser, password: e.target.value })} /><select value={newUser.role} onChange={e => setNewUser({ ...newUser, role: e.target.value })}><option value="TALENT">Talent</option><option value="RECRUITER">Recruiter</option></select><button className="solid">Create</button></form></div><div className="directory-admin"><div className="admin-toolbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search accounts, roles, locations..." /><select value={role} onChange={e => setRole(e.target.value)}><option value="ALL">All roles</option><option value="TALENT">Talents</option><option value="RECRUITER">Recruiters</option></select><select value={status} onChange={e => setStatus(e.target.value)}><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="DISABLED">Disabled</option></select></div>{loading ? <div className="admin-empty">Loading command centre…</div> : filtered.length ? <div className="user-table">{filtered.map(u => <UserRow key={u.id} u={u} working={working} grant={grant} toggle={toggle} remove={remove} />)}</div> : <div className="admin-empty">No accounts match these filters.</div>}</div></section>
}
function Stat({ n, label }) { return <div className="stat"><strong>{String(n).padStart(2, '0')}</strong><span>{label}</span></div> }
function UserRow({ u, working, grant, toggle, remove }) { const sub = u.subscriptions?.find(s => s.status === 'ACTIVE' && (!s.endsAt || new Date(s.endsAt) > new Date())); return <div className="user-row"><div className="user-main"><div className="avatar">{initials(u.name)}</div><div><strong>{u.name}</strong><span>{u.email}</span><small>{u.role}{u.talent?.professionalRole ? ` · ${u.talent.professionalRole}` : ''}{u.talent?.location ? ` · ${u.talent.location}` : ''}</small></div></div><div className="user-status"><span className={`status-dot ${u.isActive ? 'on' : 'off'}`}></span>{u.isActive ? 'Active' : 'Disabled'}</div><div className="sub-status">{sub ? <><b>{sub.plan}</b><span>{sub.amount === 0 ? 'Complimentary' : 'Paid'} · {sub.endsAt ? new Date(sub.endsAt).toLocaleDateString() : 'No expiry'}</span></> : <span>No active plan</span>}</div><div className="user-actions"><button className="glass" onClick={() => toggle(u)}>{u.isActive ? 'Disable' : 'Enable'}</button><button className="glass" onClick={() => remove(u)}>Delete</button><div className="grant-menu"><button className="solid" disabled={!!working}>Grant free ↗</button><div className="grant-pop"><button onClick={() => grant(u.id, 'PRO')}>PRO · 365d</button><button onClick={() => grant(u.id, 'EXCLUSIVE')}>Exclusive · 365d</button><button onClick={() => grant(u.id, 'ELITE')}>Elite · 365d</button></div></div></div></div> }
function Field({ label, children }) { return <label>{label}{children}</label> } function Error({ text }) { return text ? <p className="error">{text}</p> : null }
createRoot(document.getElementById('root')).render(<App />);
